"use client";

import React, { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Lang = "uz" | "ru" | "en";
export const LANGS: Array<{ value: Lang; label: string; name: string }> = [
  { value: "uz", label: "UZ", name: "O‘zbek" },
  { value: "ru", label: "RU", name: "Русский" },
  { value: "en", label: "EN", name: "English" },
];

type Dict = Record<string, string>;
const uz: Dict = {
  appName: "qanot", dashboard: "Dashboard", finance: "Moliya", debts: "Qarzdorlar", sklad: "Sklad", sales: "Sotuv", reports: "Hisobot", settings: "Sozlamalar", logout: "Chiqish", dark: "Tungi", light: "Kunduzgi", language: "Til", theme: "Rejim", save: "Saqlash", cancel: "Bekor qilish", search: "Qidirish", all: "Hammasi", allCurrency: "Barcha valuta", usd: "USD", uzs: "UZS",
  dashboardSubtitle: "Biznes holati: pul, qarz, sklad va sotuv bitta ekranda.", ownerPanel: "Boshqaruv paneli", todayIncome: "Bugungi tushum", debtRisk: "Qarz riski", warehouseValue: "Sklad qiymati", businessHealth: "Biznes holati", money: "Pul", debt: "Qarz", stock: "Sklad", remaining: "Qoldiq", overdue: "Kechikkan", opened: "Ochiq", paid: "To‘langan", closed: "Yopilgan", activeDebts: "Ochiq qarz",
  financeSubtitle: "Buxgalter uchun kassa, bank, kirim, chiqim va to‘lovlar.", todayUZS: "Bugungi UZS", todayUSD: "Bugungi USD", totalPaidUZS: "Jami to‘langan UZS", totalPaidUSD: "Jami to‘langan USD", financeActions: "Buxgalter amallari", enterPayment: "To‘lov kiritish", incomeExpense: "Kirim / chiqim", dailyReport: "Kunlik hisobot", accountantChecklist: "Buxgalter nazorati", checklist1: "Kassa va bankni solishtirish", checklist2: "Bugungi tushumlarni tekshirish", checklist3: "Kechikkan qarzdorlarni ajratish", recentPayments: "Oxirgi to‘lovlar", noRecentPayments: "To‘lovlar hali yo‘q.", client: "Mijoz", phone: "Telefon", amount: "Summa", method: "Usul",
  debtPageSubtitle: "Excel / 1C qarzdorlar. Kollektor uchun sodda ro‘yxat va tez to‘lov.", debtCenter: "Excel qarz markazi", debtCenterSub: "Import bosilganda eski qarzlar tozalanadi. Excel yagona manba bo‘ladi.", addDebt: "Qarz qo‘shish", addPayment: "To‘lov kiritish", collectorList: "Qarzdorlar", collectorListSub: "Avval mijoz ko‘rinadi. Bosilganda detallar ochiladi.", lastPayment: "Oxirgi to‘lov", noPayment: "to‘lov yo‘q", dueDate: "Muddat", status: "Holat", collector: "Kollektor", note: "Izoh", productInfo: "Nima olgan", exportExcel: "Excel export", importExcel: "Excel import",
  skladSubtitle: "MoySklad uslubidagi qoldiq hisoboti: tovar, ombor, qoldiq, prixod va prodaja narxi.", productCount: "Tovarlar", warehouseCount: "Omborlar", stockQty: "Jami qoldiq", skladValue: "Sklad qiymati", productCatalog: "Tovarlar qoldiq hisoboti", productCatalogSub: "Buxgalter uchun kerakli maydonlar: nomi, artikul, kategoriya, qoldiq, sotib olish narxi, sotuv narxi va summa.", product: "Tovar", modelSku: "Model / SKU", category: "Kategoriya", barcode: "Shtrixkod", quantity: "Qoldiq", reserve: "Rezerv", inTransit: "Yo‘lda", costPrice: "Prixod narxi", salePrice: "Prodaja narxi", costSum: "Prixod summa", saleSum: "Prodaja summa", margin: "Farq", warehouse: "Ombor", syncSettings: "Sync sozlamalari", noProducts: "Tovarlar topilmadi.", filterCategory: "Kategoriya", stockFilter: "Qoldiq holati", onlyInStock: "Faqat qoldiq bor", zeroStock: "Nol qoldiq", negativeStock: "Minus qoldiq",
  reportsSubtitle: "Egaga tushunarli hisobotlar: pul, qarz, sklad va top xavflar.", debtStatuses: "Qarz holati", topDebtors: "Top qarzdorlar", dailyPayments: "Kunlik to‘lovlar", totalDebt: "Jami qarz", paidAmount: "To‘langan", profit: "Foyda", salesTrend: "Savdo trendlari",
  settingsSubtitle: "Til, ko‘rinish va profil sozlamalari.", interface: "Interfeys", interfaceSub: "Til va tema shu yerda o‘zgaradi.", profile: "Profil", company: "Kompaniya", security: "Xavfsizlik",
};
const ru: Dict = {
  appName: "qanot", dashboard: "Дашборд", finance: "Финансы", debts: "Должники", sklad: "Склад", sales: "Продажи", reports: "Отчёты", settings: "Настройки", logout: "Выйти", dark: "Тёмная", light: "Светлая", language: "Язык", theme: "Режим", save: "Сохранить", cancel: "Отмена", search: "Поиск", all: "Все", allCurrency: "Все валюты", usd: "USD", uzs: "UZS",
  dashboardSubtitle: "Состояние бизнеса: деньги, долги, склад и продажи на одном экране.", ownerPanel: "Панель управления", todayIncome: "Поступления сегодня", debtRisk: "Риск долгов", warehouseValue: "Стоимость склада", businessHealth: "Состояние бизнеса", money: "Деньги", debt: "Долг", stock: "Склад", remaining: "Остаток", overdue: "Просрочено", opened: "Открыто", paid: "Оплачено", closed: "Закрыто", activeDebts: "Открытые долги",
  financeSubtitle: "Касса, банк, приход, расход и платежи для бухгалтера.", todayUZS: "Сегодня UZS", todayUSD: "Сегодня USD", totalPaidUZS: "Оплачено UZS", totalPaidUSD: "Оплачено USD", financeActions: "Действия бухгалтера", enterPayment: "Внести платёж", incomeExpense: "Приход / расход", dailyReport: "Дневной отчёт", accountantChecklist: "Контроль бухгалтера", checklist1: "Сверить кассу и банк", checklist2: "Проверить сегодняшние поступления", checklist3: "Выделить просроченных должников", recentPayments: "Последние платежи", noRecentPayments: "Платежей пока нет.", client: "Клиент", phone: "Телефон", amount: "Сумма", method: "Метод",
  debtPageSubtitle: "Должники из Excel / 1C. Удобный список для коллектора и быстрый платёж.", debtCenter: "Центр долгов Excel", debtCenterSub: "При импорте старые долги очищаются. Excel становится единственным источником.", addDebt: "Добавить долг", addPayment: "Внести платёж", collectorList: "Должники", collectorListSub: "Сначала виден клиент. Детали открываются по нажатию.", lastPayment: "Последний платёж", noPayment: "платежей нет", dueDate: "Срок", status: "Статус", collector: "Коллектор", note: "Комментарий", productInfo: "Что купил", exportExcel: "Экспорт Excel", importExcel: "Импорт Excel",
  skladSubtitle: "Отчёт остатков в стиле MoySklad: товар, склад, остаток, закупка и продажа.", productCount: "Товары", warehouseCount: "Склады", stockQty: "Общий остаток", skladValue: "Стоимость склада", productCatalog: "Отчёт по остаткам", productCatalogSub: "Нужные поля для бухгалтера: товар, артикул, категория, остаток, закупочная цена, продажная цена и сумма.", product: "Товар", modelSku: "Модель / SKU", category: "Категория", barcode: "Штрихкод", quantity: "Остаток", reserve: "Резерв", inTransit: "В пути", costPrice: "Закупка", salePrice: "Продажа", costSum: "Сумма закупки", saleSum: "Сумма продажи", margin: "Разница", warehouse: "Склад", syncSettings: "Настройки синхронизации", noProducts: "Товары не найдены.", filterCategory: "Категория", stockFilter: "Состояние остатка", onlyInStock: "Только с остатком", zeroStock: "Нулевой остаток", negativeStock: "Минусовой остаток",
  reportsSubtitle: "Понятные отчёты для владельца: деньги, долги, склад и ключевые риски.", debtStatuses: "Статусы долгов", topDebtors: "Топ должники", dailyPayments: "Платежи по дням", totalDebt: "Общий долг", paidAmount: "Оплачено", profit: "Прибыль", salesTrend: "Тренд продаж",
  settingsSubtitle: "Язык, тема и профиль.", interface: "Интерфейс", interfaceSub: "Язык и тема меняются здесь.", profile: "Профиль", company: "Компания", security: "Безопасность",
};
const en: Dict = {
  appName: "qanot", dashboard: "Dashboard", finance: "Finance", debts: "Debtors", sklad: "Stock", sales: "Sales", reports: "Reports", settings: "Settings", logout: "Logout", dark: "Dark", light: "Light", language: "Language", theme: "Theme", save: "Save", cancel: "Cancel", search: "Search", all: "All", allCurrency: "All currencies", usd: "USD", uzs: "UZS",
  dashboardSubtitle: "Business status: money, debts, stock and sales on one screen.", ownerPanel: "Control panel", todayIncome: "Today income", debtRisk: "Debt risk", warehouseValue: "Stock value", businessHealth: "Business health", money: "Money", debt: "Debt", stock: "Stock", remaining: "Remaining", overdue: "Overdue", opened: "Open", paid: "Paid", closed: "Closed", activeDebts: "Open debts",
  financeSubtitle: "Cash, bank, income, expenses and payments for accountants.", todayUZS: "Today UZS", todayUSD: "Today USD", totalPaidUZS: "Paid UZS", totalPaidUSD: "Paid USD", financeActions: "Accountant actions", enterPayment: "Enter payment", incomeExpense: "Income / expense", dailyReport: "Daily report", accountantChecklist: "Accountant control", checklist1: "Reconcile cash and bank", checklist2: "Check today’s receipts", checklist3: "Separate overdue debtors", recentPayments: "Recent payments", noRecentPayments: "No payments yet.", client: "Client", phone: "Phone", amount: "Amount", method: "Method",
  debtPageSubtitle: "Debtors from Excel / 1C. Simple collector list and quick payment entry.", debtCenter: "Excel debt center", debtCenterSub: "Import clears old debts. Excel becomes the single source.", addDebt: "Add debt", addPayment: "Enter payment", collectorList: "Debtors", collectorListSub: "Client is shown first. Click to open details.", lastPayment: "Last payment", noPayment: "no payments", dueDate: "Due date", status: "Status", collector: "Collector", note: "Note", productInfo: "Purchase", exportExcel: "Export Excel", importExcel: "Import Excel",
  skladSubtitle: "MoySklad-style stock report: product, warehouse, quantity, cost and sale price.", productCount: "Products", warehouseCount: "Warehouses", stockQty: "Total stock", skladValue: "Stock value", productCatalog: "Stock report", productCatalogSub: "Accountant fields: product, SKU, category, stock, purchase price, sale price and total.", product: "Product", modelSku: "Model / SKU", category: "Category", barcode: "Barcode", quantity: "Stock", reserve: "Reserve", inTransit: "In transit", costPrice: "Purchase", salePrice: "Sale", costSum: "Purchase total", saleSum: "Sale total", margin: "Margin", warehouse: "Warehouse", syncSettings: "Sync settings", noProducts: "No products found.", filterCategory: "Category", stockFilter: "Stock state", onlyInStock: "Only in stock", zeroStock: "Zero stock", negativeStock: "Negative stock",
  reportsSubtitle: "Clear owner reports: money, debts, stock and key risks.", debtStatuses: "Debt statuses", topDebtors: "Top debtors", dailyPayments: "Daily payments", totalDebt: "Total debt", paidAmount: "Paid", profit: "Profit", salesTrend: "Sales trend",
  settingsSubtitle: "Language, theme and profile settings.", interface: "Interface", interfaceSub: "Change language and theme here.", profile: "Profile", company: "Company", security: "Security",
};
const dictionary: Record<Lang, Dict> = { uz, ru, en };

export type I18nValue = { lang: Lang; setLang: (lang: Lang) => void; t: (key: string, fallback?: string) => string };
function normalizeLang(value: string | null): Lang { return value === "ru" || value === "en" || value === "uz" ? value : "uz"; }
const I18nContext = createContext<I18nValue>({ lang: "uz", setLang: () => {}, t: (key, fallback) => fallback || key });
export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("uz");
  useEffect(() => { setLangState(normalizeLang(localStorage.getItem("qanot_lang") || localStorage.getItem("operix_lang"))); }, []);
  function setLang(next: Lang) { setLangState(next); localStorage.setItem("qanot_lang", next); localStorage.setItem("operix_lang", next); }
  const value = useMemo(() => ({ lang, setLang, t: (key: string, fallback?: string) => dictionary[lang]?.[key] || fallback || key }), [lang]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n() { return useContext(I18nContext); }
export function t(key: string, fallback?: string) { return dictionary.uz[key] || fallback || key; }
